services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $locale: '%locale%'

    App\Tests\Behat\Context\:
        resource: '../tests/Behat/Context/*'

    App\Tests\Services\:
        resource: '../tests/Services/*'

    Doctrine\Common\DataFixtures\Purger\ORMPurger: ~
    Doctrine\ORM\Tools\SchemaTool: ~

    App\Tests\Services\ReferencesInterface: '@App\Tests\Services\FlushingReferences'
    App\Tests\Services\FlushingReferences:
        arguments:
            $inner: '@App\Tests\Services\References'
